### ISSUE TITLE
怎么得到chatgpt的回复

### ISSUE THREAD

**Issue by jiangweiatgithub** [mostlittlebee/chatgpt-on-wecom#10]
我已经自建好企业微信应用，并且已经启用了API接收（看到服务器端显示200）。我用个人微信扫那个企业微信，成功入群，发送消息别人也能看见（但得不到chatgpt的任何回复）。我现在的问题是，如何让chatgpt参与讨论（回复问题）？是需要特别的指令或at谁一下吗？

**Comment by mostlittlebee** [comment]
企业微信的应用号不支持入群讨论
