### ISSUE TITLE
企业微信配置该如何获取

### ISSUE THREAD

**Issue by xyfacai** [mostlittlebee/chatgpt-on-wecom#3]
```
  "WECHAT_TOKEN": "企业微信 回调token",
  "WECHAT_ENCODING_AES_KEY":"企业微信 编码后的AES Key",
  "WECHAT_CORP_ID":"企业微信 企业ID",
  "Secret":"企业微信 应用Secret",
  "AppId":"企业微信 应用ID",
```
  
我创建了个企业微信，以前没有配置过，不太清楚，请教一下，谢谢。
看了开发者中心创建的，比较像，https://developer.work.weixin.qq.com/tool#/tab/apps/list
但是搜教程又是在应用管理里配置，搞不清楚。。
应用管理里配置的只看到 AppId，Secret
WECHAT_TOKEN、WECHAT_ENCODING_AES_KEY 只在开发者中心文档里看到

**Comment by mostlittlebee** [comment]
"WECHAT_CORP_ID":"企业微信 企业ID",  是全局唯一的，可以在企业微信后台管理里的企业信息里查看。
WECHAT_TOKEN ： 是你自己设置的回调token，在应用管理中配置（自己创建的应用）
WECHAT_ENCODING_AES_KEY：是你自己设置的AES Key，也是在应用管理中配置（自己创建的应用）
