### ISSUE TITLE
wechatenterprise_channel.py文件中并没有WechatEnterpriseChannel的class，却在channel_factory.py文件中导入了这个类

### ISSUE THREAD

**Issue by 95i** [mostlittlebee/chatgpt-on-wecom#4]
wechatenterprise_channel.py文件中并没有WechatEnterpriseChannel的class，却在channel_factory.py文件中导入了这个类

刚开始就报错，根本就没有运行到检测config文件是否存在

**Comment by chenny** [comment]
20:18 # python3 app.py
Traceback (most recent call last):
  File "/app/wwwroot/chatgpt-on-wecom/app.py", line 3, in <module>
    from channel import channel_factory
  File "/app/wwwroot/chatgpt-on-wecom/channel/channel_factory.py", line 6, in <module>
    from channel.wechatcom.wechatenterprise_channel import WechatEnterpriseChannel
ImportError: cannot import name 'WechatEnterpriseChannel' from 'channel.wechatcom.wechatenterprise_channel' (/app/wwwroot/chatgpt-on-wecom/channel/wechatcom/wechatenterprise_channel.py)

我也碰到了同样的问题

**Comment by mostlittlebee** [comment]
重新更新了下，初始版本居然没上传最终的版本
