### ISSUE TITLE
WechatEnterpriseChannel里面错误比较多. 

### ISSUE THREAD

**Issue by chenny** [mostlittlebee/chatgpt-on-wecom#5]
WechatEnterpriseChannel里面的 handle 两个参数是报错的. 去掉的话, _do_send报错. 你跑起来了吗
![image](https://user-images.githubusercontent.com/883329/220136607-712260ed-bab6-4fdf-8205-89a0687e5b56.png)
<img width="737" alt="image" src="https://user-images.githubusercontent.com/883329/220136846-50cfe288-cbc1-4ec9-92b5-13b0bc45d183.png">

**Comment by mostlittlebee** [comment]
重新更新了下，初始版本居然没上传最终的版本
