### ISSUE TITLE
企业微信自建应用的配置

### ISSUE THREAD

**Issue by colozhan** [mostlittlebee/chatgpt-on-wecom#6]
请问企业微信后台自建应用中接收消息服务器配置段的url应该怎么配置？在保存时一直提示openapi回调地址请求不通过

**Comment by colozhan** [comment]
测试时nohup日志提示GET请求404

**Comment by mostlittlebee** [comment]
你的网站域名+ /wechat/2023年2月28日 18:13，Allen ***@***.***>写道：

测试时nohup日志提示GET请求404

**Comment by colozhan** [comment]
如您所提示的在域名后面加上尝试了加上/wechat和/wechat/，其中/wechat在后端日志能看到get请求成功状态码为200，/wechat/为404，但均提示openapi回调地址请求不通过，在浏览器将日志里的url接后get页面提示success

**Comment by mostlittlebee** [comment]
贴个图看下你的设置参数？可以模糊掉部分url和key值

**Comment by colozhan** [comment]
![617b997888f351ee44cbfa208a8f648](https://user-images.githubusercontent.com/5457816/222340949-c4631d8b-6e26-47ee-9524-ce58469660af.png)
![c7ac4dc3692f25ec81210929fc44cfb](https://user-images.githubusercontent.com/5457816/222340961-2be9090a-91ae-4275-8aa1-efb243a2c7fc.png)
如图所示

**Comment by mostlittlebee** [comment]
![image](https://user-images.githubusercontent.com/66151739/222423040-af100b38-7d11-4f27-9855-5c4bbfb946ef.png)
我是这样配置的，URL需要主机名带上/wechat 的。

如果配置正常，服务端会打印出收到的URL

**Comment by colozhan** [comment]
服务端确实正常接收到了，但是企业微信端似乎没有收到反馈，一直提示openapi回调地址请求不通过
![image](https://user-images.githubusercontent.com/5457816/222669040-fffbda7b-a8a0-48d3-98ed-786a27b3e0a5.png)

**Comment by mostlittlebee** [comment]
1.要不换下key试试
2.在返回这里增加日志输出看看return的内容

**Comment by mostlittlebee** [comment]
你的日志显示了2月28日的输出，没有最新的吗

**Comment by colozhan** [comment]
后面就没再尝试了

**Comment by Doject** [comment]
channel/wechatcom/wechatenterprise_channel.py
def handler_msg():
WechatEnterpriseChannel().handle()
return 'success'

改成 下面就可以了
def handler_msg():
return WechatEnterpriseChannel().handle()
#return 'success'

**Comment by colozhan** [comment]
> channel/wechatcom/wechatenterprise_channel.py def handler_msg(): WechatEnterpriseChannel().handle() return 'success'
> 
> 改成 下面就可以了 def handler_msg(): return WechatEnterpriseChannel().handle() #return 'success'

收到，变更后api配置成功，后台能接收到相关请求，但不知是接口原因还是什么，没有返回相关数据，如图
![image](https://user-images.githubusercontent.com/5457816/222773407-cd02d556-165c-423e-a80c-e8cb1de4c30b.png)
![image](https://user-images.githubusercontent.com/5457816/222773483-1e718dc1-f622-4fd9-a363-3d9be9de09b6.png)

**Comment by colozhan** [comment]
似乎知晓原因了，可能是无法与api进行连接吧，后续后台返回` Failed to establish a new connection: [Errno 101] Network is unreachable'))`

**Comment by Doject** [comment]
> 

昨天晚上 开始 国内大面积被墙了.

**Comment by lam2018** [comment]
挂着clash的话可以正常使用

**Comment by colozhan** [comment]
> 挂着clash的话可以正常使用

已解决 thx

**Comment by mostlittlebee** [comment]
> 

感谢支持问题，已修改。
