### ISSUE TITLE
openapi回调地址请求不通过

### ISSUE THREAD

**Issue by lam2018** [mostlittlebee/chatgpt-on-wecom#7]
我在本地clone项目并运行，在访问地址http://10.10.10.8:8888/wechat时出现报错提示如下：
Forbidden
You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.
终端显示：” "GET /wechat HTTP/1.1" 403 -“

在访问地址http://10.10.10.8:8888/wechat/时出现报错提示如下：
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
终端显示："GET /wechat/ HTTP/1.1" 404 -

另外，我的问题其实是在保存“微信企业号的接收消息服务器配置” 时提示 “openapi回调地址请求不通过”。看到lssues中有相关讨论作者表示需要在域名加上/wechat或/wechat/，这两个路径测试下来依旧提示“openapi回调地址请求不通过”。所以在本地进行测试出现上述问题。

请问：
1、微信企业号在添加应用后除了配置”接收消息“还有无其它配置（如网页授权及JS-SDK，企业可信IP等）

我已做过的测试：
1、为chatgpt-on-wecom整个目录添加777权限

我的环境：
ubuntu 20.04
python 3.8

我的配置：
![微信图片编辑_20230303222616](https://user-images.githubusercontent.com/48943186/222745988-1c84a6ac-90ef-46bb-b970-19459e998e2e.jpg)

<img width="526" alt="微信图片_20230303222905" src="https://user-images.githubusercontent.com/48943186/222746200-46534a1f-ba9b-4d38-af70-d175f74875e1.png">

**Comment by Doject** [comment]
一摸一样的问题,我看了他这个文件wechatcom/wechatenterprise_channel.py   处理回调 是返回一个success,可我查了资料说 要反馈解密后的字符串,搞不懂...没有具体资料

**Comment by Doject** [comment]
要加上token的吧 
http://domain/wechat?msg_signature=de17da9a616a0874130616bca0ebcea95d70553e&timestamp=1677855506&nonce=1678343232&echostr=buEvukPcBQehJI2y5a67DrhJkCf7r7xVhK69xDZbmyHDKQfLABxoOdkMUjQa9HzKPVKwhVGuW6k107Br1ZaejA%3D%3D

**Comment by Doject** [comment]
channel/wechatcom/wechatenterprise_channel.py 
def handler_msg():
     WechatEnterpriseChannel().handle()
    return 'success'

改成  下面就可以了
def handler_msg():
    return WechatEnterpriseChannel().handle()
    #return 'success'

**Comment by lam2018** [comment]
> channel/wechatcom/wechatenterprise_channel.py def handler_msg(): WechatEnterpriseChannel().handle() return 'success'
> 
> 改成 下面就可以了 def handler_msg(): return WechatEnterpriseChannel().handle() #return 'success'



感谢回复，在参考这个修改操作后。我依旧回调提求不通过并在终端得到如下提示：

TypeError: __init__() missing 1 required positional argument: 'backend'
43.137.215.241 - - [03/Mar/2023 15:52:38] "GET /wechat?msg_signature=31a9638997216d5f5SDFxd88ace92f901af7513e&timestamp=167787887758&nonce=1678985613&echostr=2FmXxqSDDFvslxLWXXXXrlnn3XXXX1kNi2a36sYmL+WOVPXXXnLQ5gDDD%3D HTTP/1.1" 500 -

**Comment by lam2018** [comment]
> 
最后在参考Doject的方法，并重新安装cryptography和OpenSSL后现在可以正常使用了，响应速度也很快。

**Comment by forydar** [comment]
加一个，需要在企业微信应用中，设置可信IP，不然消息无法回发
