### ISSUE TITLE
企业微信应用的api接收消息

### ISSUE THREAD

**Issue by gzh540639382** [mostlittlebee/chatgpt-on-wecom#8]
最上面的url地址该怎么填

**Comment by Suevivian** [comment]
ip:port/wechat

**Comment by gzh540639382** [comment]
![image](https://user-images.githubusercontent.com/33572207/223647576-caf485fc-53e2-4e0f-a16e-a54b7444eec1.png)
报错了

**Comment by gzh540639382** [comment]
看到了，配置文件少了个”
